import 'dart:io' as std_io;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'google_translate_service.dart';

/// AppLocalizations provides multi-language translations across 8 languages:
/// Urdu (ur), English (en), Arabic (ar), Hindi (hi), Telugu (te), Kannada (kn), Tamil (ta), Malayalam (ml).
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ur'));
  }

  static const _localizedValues = <String, Map<String, String>>{
  'ur': {
      'app_title': 'مکتب مینیجر',
      'late': 'تاخیر',
      'select': 'منتخب',
      'cap_uniform_books': 'ٹوپی / یونیفارم / کتابیں',
      'late_arrival': 'دیر سے آیا',
      'attendance_tap': 'حاضری\n(کلک کریں)',
      'student_father_header': 'طالب علم کا نام\nوالد کا نام',
      'notifications_center': 'نوٹیفکیشنز سینٹر',
      'prev_attendance_saved': 'پچھلی حاضری کامیابی سے محفوظ ہو گئی۔',
      'new_admin_msg': 'ایڈمن کی جانب سے نیا پیغام موصول ہواے۔',
      'student_attendance_list': 'طلبہ کی حاضری لسٹ',
      'hardware_test_tool': 'مائیک و کیمرہ فنکشنلٹی ٹیسٹ ٹول',
      'mic_test_title': 'مائیک و وائس ریکگنیشن ٹیسٹ',
      'camera_test_title': 'کیمرہ فوٹو ٹیسٹ',
      'test_mic_btn': 'مائیک ٹیسٹ کریں',
      'test_camera_btn': 'کیمرہ ٹیسٹ کریں',
      'close': 'بند کریں',
      'students_list': 'طلبہ کی فہرست',
      'add_student': 'نیا طالب علم شامل کریں',
      'edit_student': 'طالب علم کی تفصیلات ایڈٹ کریں',
      'delete_student': 'حذف کریں',
      'search_hint': 'نام، داخلہ نمبر، یا والد کے نام سے تلاش کریں...',
      'name': 'نام',
      'roll_no': 'داخلہ نمبر / Roll No',
      'phone_number': 'موبائل نمبر / فون',
      'class_grade': 'کلاس / درجہ',
      'shift': 'شفٹ',
      'morning': 'صبح',
      'evening': 'شام',
      'gender': 'جنس',
      'male': 'لڑکا',
      'female': 'لڑکی',
      'teacher_name': 'استاد کا نام',
      'notice_channel': 'نوٹس کا ذریعہ',
      'message_language': 'پیغام کی زبان',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'fee_record': 'فیس کا کھاتہ',
      'fee_amount': 'فیس کی رقم',
      'select_month': 'مہینہ منتخب کریں',
      'fee_status': 'فیس کی صورتحال',
      'due': 'غیر ادا شدہ / واجب الادا',
      'partially_paid': 'جزوی ادا شدہ',
      'paid': 'مکمل ادا شدہ',
      'attendance': 'حاضری',
      'present': 'حاضر',
      'absent': 'غیر حاضر',
      'leave': 'رخصت',
      'sabaq_lessons': 'سبق و تلاوت',
      'total_students': 'کل طلبہ',
      'apply_to_all': 'سب پر لاگو کریں',
      'change_teacher': 'استاد کا نام تبدیل کریں',
      'change_topic': 'آج کا موضوع تبدیل کریں',
      'book_name': 'کتاب کا نام',
      'lesson_surah': 'سبق / سورت',
      'total': 'کل',
      'collected': 'وصول شدہ',
      'actions': 'کارروائی',
      'select_language': 'زبان منتخب کریں',
      'urdu': 'اردو',
      'english': 'English',
      'arabic': 'العربية',
      'hindi': 'हिंदी',
      'telugu': 'తెలుగు',
      'kannada': 'ಕನ್ನಡ',
      'tamil': 'தமிழ்',
      'malayalam': 'മലയാളം',
      'no_students_found': 'کوئی طالب علم نہیں ملا',
      'confirm_delete': 'کیا آپ واقعی اس طالب علم کو حذف کرنا چاہتے ہیں؟',
      'view_sabaq': 'سبق دیکھیں',
      'call': 'کال کریں',
      'whatsapp': 'WhatsApp',
      'all': 'تمام',
      'analytics': 'ایڈوانسڈ ڈیش بورڈ',
      'theme_mode': 'تھیم تبدیل کریں',
      'print_pdf': 'PDF پرنٹ کریں',
      'fee_receipt': 'فیس رسید',
      'report_card': 'تعلیمی رپورٹ کارڈ',
      'consecutive_absent_alert': 'مسلسل غیر حاضری کا الرٹ',
      'consecutive_absent_desc': 'یہ طلبہ مسلسل 3 یا اس سے زیادہ دنوں سے غیر حاضر ہیں',
      'total_due_amount': 'کل واجب الادا رقم',
      'total_paid_amount': 'کل وصول شدہ رقم',
      'attendance_rate': 'حاضری کا تناسب',
      'select_role': 'اپنا کردار منتخب کریں',
      'full_name': 'مکمل نام',
      'pin': 'پن (PIN)',
      'confirm_pin': 'پن کی تصدیق',
      'welcome': 'خوش آمدید',
      'continue_btn': 'آگے بڑھیں',
      'login': 'لاگ ان کریں',
      'new_admission': 'نیا داخلہ',
      'old_admission': 'قدیم طالب علم',
      'advanced_dashboard': 'ایڈوانسڈ ڈیش بورڈ',
      'staff_logins': 'اسٹاف PINs کا انتظام',
      'parent_logins': 'والدین کے PINs کا انتظام',
      'create_group': 'کلاس و گروپ بنائیں',
      'attendance_ledger': 'حاضری کا کھاتہ',
      'lesson_plan': 'سبق و تلاوت',
      'student_name': 'طالب علم کا نام',
      'father_name': 'والد/سرپرست کا نام',
      'father_phone': 'والد/سرپرست کا موبائل نمبر',
      'admission_date': 'تاریخ داخلہ',
      'batch_group': 'بیچ گروپ',
      'shift_timing': 'شفٹ کا وقت',
      'overview': 'مجموعی جائزہ',
      'quick_actions': 'فوری اقدامات',
      'mark_attendance': 'حاضری درج کریں',
      'fee_portal': 'فیس پورٹل',
      'community_chat': 'کمیونٹی و پیغام رسانی',
      'results_performance': 'نتائج و کارکردگی',
      'admin_control': 'ایڈمن کنٹرول پورٹل',
      'leave_portal': 'رخصت پورٹل',
      'fee_collection': 'فیس وصولی',
      'attendance_result': 'حاضری کا نتیجہ',
      'teacher_attendance_status': 'اساتذہ کی حاضری کی صورتحال',
      'recorded_by_teacher': 'استاد کا درج کردہ حاضری ریکارڈ',
      'madrasa_title': 'مدرسہ خیر العلوم اشرفیہ',
      'select_subject': 'سبجیکٹ سلیکشن',
      'lesson_entry_title': 'سبق کی انٹری (بولیں یا لکھیں)',
      'dars_entry_title': 'درس کی انٹری (کلاس میں)',
      'save_all_entries': 'تمام اندراجات محفوظ کریں',
      'save_as_pdf': 'پی ڈی ایف محفوظ کریں',
      'mark_all_yaad_hai': 'سب کو یاد ہے نشان زد کریں',
      'mark_all_iaadah': 'سب کو اعادہ نشان زد کریں',
      'id_card': 'شناختی کارڈ',
      'promote': 'ترقیِ درجہ',
      'certificate': 'سندِ فراغت',
      'maktab_rules': 'قواعد',
      'permissions': 'اجازتیں',
      'db_import_export': 'داتابیس بیک اپ اور ری سٹور',
      'security_logins': 'سیکیورٹی و لاگ ان انتظام',
      'student_academic_controls': 'طلبہ و تعلیمی انتظامیہ',
      'remember_me': 'معلومات یاد رکھیں',
      'forgot_pin': 'PIN بھول گئے؟',
      'login_btn': 'لاگ ان کریں',
      'create_account_btn': 'نیا اکاؤنٹ بنائیں اور داخل ہوں',
      'create_account': 'نیا اکاؤنٹ بنائیں',
      'biometric_login': 'فنگر پرنٹ / بائیو میٹرک لاگ ان',
      'last_login': 'آخری کامیاب لاگ ان',
      'pin_recovery': 'پن (PIN) کی بازیابی',
      'pin_recovery_msg': 'اگر آپ اپنا PIN بھول گئے ہیں تو ایڈمن یا متعلقہ استاد سے رابطہ کریں۔',
      'ok': 'ٹھیک ہے',
      'account_created': 'نیا اکاؤنٹ کامیابی سے رجسٹر ہو گیا!',
      'error_phone_pin': 'براہ کرم فون نمبر اور پن درج کریں',
      'error_name_required': 'براہ کرم اپنا پورا نام درج کریں',
      'error_phone_invalid': 'براہ کرم درست فون نمبر درج کریں',
      'error_pin_short': 'پن کم از کم 4 ہندسوں کا ہونا چاہیے',
      'error_pin_mismatch': 'پن کی تصدیق میچ نہیں ہوئی',
      'error_wrong_pin': 'غلط فون نمبر یا پن',
      'attempts_remaining': 'باقی کوششیں',
      'security_lock': 'سیکیورٹی لاک',
      'seconds_remaining': 'سیکنڈز باقی',
      'too_many_attempts': 'بہت سی غلط کوششیں!',
      'staff_attendance': 'عملے و اساتذہ کی حاضری',
      'staff_attendance_saved': 'اساتذہ کی حاضری محفوظ ہو گئی',
      'expenses': 'مکتب آمدن و اخراجات',
      'substitute_teacher': 'متبادل استاد کی ڈیوٹی',
      'substitute_desc': 'غیر حاضر استاد کے لیے متبادل استاد مقرر کریں',
      'dropout_analytics': 'ترکِ تعلیم کا رجسٹر',
      'reason': 'وجہ',
      'audit_log': 'ایڈمن ہسٹری و لاگز',
      'select_branch': 'مکتب شاخیں',
      'backup_desc': 'مکتب کے تمام ڈاٹا کا بیک اپ لیں یا بحال کریں',
      'class_promotion': 'کلاس میں ترقی',
      'promote_confirm': 'کیا آپ تمام طلبہ کو اگلی کلاس میں ترقی دینا چاہتے ہیں؟',
      'promote_all': 'ترقی دیں',
      'students_promoted': 'تمام طلبہ کو اگلی کلاس میں منتقل کر دیا گیا',
      'leaving_cert': 'سندِ فراغت',
      'add_expense': 'نیا خرچ درج کریں',
      'substitute_duty': 'متبادل استاد ڈیوٹی',
      'code_of_conduct': 'مکتب قواعد و ضوابط',
      'rule_punctuality': 'وقت کی پابندی لازم ہے',
      'rule_dress': 'صاف ستھرا لباس اور ٹوپی پہن کر آئیں',
      'rule_absence': '3 دن مسلسل غیر حاضری پر داخلہ منسوخ ہو سکتا ہے',
      'rule_fee': 'فیس ہر ماہ کی 10 تاریخ تک جمع کروائیں',
      'role_permissions': 'رول کی بنیاد پر اجازت نامے',
      'admin_full_access': 'ایڈمن: تمام اختیارات',
      'manager_fees_results': 'مینیجر: فیس و نتائج',
      'teacher_attendance_dars': 'استاد: حاضری و سبق',
      'mutawalli_finance': 'متولی: مالیاتی خلاصہ',
      'digital_id_card': 'ڈیجیٹل شناختی کارڈ',
      'position': 'عہدہ',
      'new_admissions': 'نئے داخلے',
      'old_admissions': 'سابقہ داخلے',
      'hifz_group': 'حفظ گروپ',
      'nazira_group': 'ناظرہ گروپ',
      'tajweed_group': 'تجوید گروپ',
      'primary_group': 'ابتدائی گروپ',
      'morning_shift': 'صبح',
      'evening_shift': 'شام',
      'good_morning': 'صبح بخیر',
      'good_afternoon': 'دوپہر بخیر',
      'good_evening': 'شام بخیر',
      'dashboard': 'ڈیش بورڈ',
      'settings': 'ترتیبات',
      'logout': 'لاگ آؤٹ',
      'about': 'ایپ کے بارے میں',
      'version': 'ورژن',
      'search': 'تلاش',
      'admin_login': 'ایڈمن لاگ ان',
      'manager_login': 'مینجر لاگ ان',
      'teacher_login': 'استاد لاگ ان',
      'parent_login': 'والدین لاگ ان',
      'mutawalli_login': 'متولی لاگ ان',
      'user_login': 'صارف لاگ ان',
      'role_tier': 'ٹائیر',
    },
  'en': {
      'app_title': 'Maktab Manager',
      'late': 'Late',
      'select': 'Select',
      'cap_uniform_books': 'Cap / Uniform / Books',
      'late_arrival': 'Late Arrival',
      'attendance_tap': 'Attendance\n(Tap)',
      'student_father_header': 'Student Name\nFather Name',
      'notifications_center': 'Notifications Center',
      'prev_attendance_saved': 'Previous attendance saved successfully.',
      'new_admin_msg': 'New message received from admin.',
      'student_attendance_list': 'Student Attendance List',
      'hardware_test_tool': 'Hardware Diagnostic Tools (Mic & Camera)',
      'mic_test_title': 'Microphone Speech-to-Text Test',
      'camera_test_title': 'Camera Capture Test',
      'test_mic_btn': 'Test Mic',
      'test_camera_btn': 'Test Camera',
      'close': 'Close',
      'students_list': 'Student List',
      'add_student': 'Add New Student',
      'edit_student': 'Edit Student Details',
      'delete_student': 'Delete',
      'search_hint': 'Search by name, roll no, or father name...',
      'name': 'Name',
      'roll_no': 'Roll No / Admission No',
      'phone_number': 'Phone Number',
      'class_grade': 'Class / Grade',
      'shift': 'Shift',
      'morning': 'Morning',
      'evening': 'Evening',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'teacher_name': 'Teacher Name',
      'notice_channel': 'Notice Channel',
      'message_language': 'Message Language',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'fee_record': 'Fee Ledger',
      'fee_amount': 'Fee Amount',
      'select_month': 'Select Month',
      'fee_status': 'Fee Status',
      'due': 'Unpaid / Due',
      'partially_paid': 'Partially Paid',
      'paid': 'Paid',
      'attendance': 'Attendance',
      'present': 'Present',
      'absent': 'Absent',
      'leave': 'Leave',
      'sabaq_lessons': 'Lesson Target',
      'total_students': 'Total Students',
      'apply_to_all': 'Apply to All',
      'change_teacher': 'Change Teacher Name',
      'change_topic': 'Change Today\'s Topic',
      'book_name': 'Book Name',
      'lesson_surah': 'Lesson / Surah',
      'total': 'Total',
      'collected': 'Collected',
      'actions': 'Actions',
      'select_language': 'Select Language',
      'urdu': 'Urdu (اردو)',
      'english': 'English',
      'arabic': 'Arabic (العربية)',
      'hindi': 'Hindi (हिंदी)',
      'telugu': 'Telugu (తెలుగు)',
      'kannada': 'Kannada (ಕನ್ನಡ)',
      'tamil': 'Tamil (தமிழ்)',
      'malayalam': 'Malayalam (മലയാളം)',
      'no_students_found': 'No students found',
      'confirm_delete': 'Are you sure you want to delete this student?',
      'view_sabaq': 'View Lesson',
      'call': 'Call',
      'whatsapp': 'WhatsApp',
      'all': 'All',
      'analytics': 'Analytics & Reports',
      'theme_mode': 'Toggle Theme',
      'print_pdf': 'Print PDF',
      'fee_receipt': 'Fee Receipt',
      'report_card': 'Report Card',
      'consecutive_absent_alert': 'Consecutive Absence Alert',
      'consecutive_absent_desc': 'These students have been absent for 3+ consecutive days',
      'total_due_amount': 'Total Due Amount',
      'total_paid_amount': 'Total Paid Amount',
      'attendance_rate': 'Attendance Rate',
      'select_role': 'Select Your Role',
      'full_name': 'Full Name',
      'pin': 'PIN',
      'confirm_pin': 'Confirm PIN',
      'welcome': 'Welcome',
      'continue_btn': 'Continue',
      'login': 'Login',
      'new_admission': 'New Admission',
      'old_admission': 'Old Student',
      'advanced_dashboard': 'Advanced Dashboard',
      'staff_logins': 'Manage Staff PINs',
      'parent_logins': 'Manage Parent PINs',
      'create_group': 'Create Class / Group',
      'attendance_ledger': 'Attendance Ledger',
      'lesson_plan': 'Lesson Plan',
      'student_name': 'Student Name',
      'father_name': 'Parent/Guardian Name',
      'father_phone': 'Parent/Guardian Phone',
      'admission_date': 'Admission Date',
      'batch_group': 'Batch Group',
      'shift_timing': 'Shift Timing',
      'overview': 'Overview',
      'quick_actions': 'Quick Actions',
      'mark_attendance': 'Mark Attendance',
      'fee_portal': 'Maktab Fee Management',
      'community_chat': 'Community Chat',
      'results_performance': 'Results & Performance',
      'admin_control': 'Admin Control Portal',
      'leave_portal': 'Leave Portal',
      'fee_collection': 'Fee Collection',
      'attendance_result': 'Attendance Result',
      'teacher_attendance_status': 'Teacher Attendance Status',
      'recorded_by_teacher': 'Attendance Recorded by Teacher',
      'madrasa_title': 'Madrasa AIB',
      'select_subject': 'Select Subject',
      'lesson_entry_title': 'Lesson Entry (Speak or Type)',
      'dars_entry_title': 'Dars Entry (In Class)',
      'save_all_entries': 'Save All Entries',
      'save_as_pdf': 'Save as PDF',
      'mark_all_yaad_hai': 'Mark All Yaad Hai',
      'mark_all_iaadah': 'Mark All Iaadah',
      'id_card': 'ID Card',
      'promote': 'Promote',
      'certificate': 'Leaving Certificate',
      'maktab_rules': 'Maktab Rules',
      'permissions': 'Permissions',
      'db_import_export': 'Database Backup & Restore',
      'security_logins': 'Security & Logins Management',
      'student_academic_controls': 'Student & Academic Controls',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'ar': {
      'app_title': 'مدير المكتب',
      'late': 'متأخر',
      'select': 'تحديد',
      'cap_uniform_books': 'القبعة / الزي / الكتب',
      'late_arrival': 'وصول متأخر',
      'attendance_tap': 'الحضور\n(انقر)',
      'student_father_header': 'اسم الطالب\nاسم الأب',
      'notifications_center': 'مركز الإشعارات',
      'prev_attendance_saved': 'تم حفظ الحضور السابق بنجاح.',
      'new_admin_msg': 'تم استلام رسالة جديدة من المشرف.',
      'student_attendance_list': 'قائمة حضور الطلاب',
      'hardware_test_tool': 'أدوات فحص الأجهزة (الميكروفون والكاميرا)',
      'mic_test_title': 'اختبار التعرف على الصوت للميكروفون',
      'camera_test_title': 'اختبار التقاط الكاميرا',
      'test_mic_btn': 'اختبار الميكروفون',
      'test_camera_btn': 'اختبار الكاميرا',
      'close': 'إغلاق',
      'students_list': 'قائمة الطلاب',
      'add_student': 'إضافة طالب جديد',
      'edit_student': 'تعديل بيانات الطالب',
      'delete_student': 'حذف',
      'search_hint': 'ابحث بالاسم أو رقم القيد أو اسم الأب...',
      'name': 'الاسم',
      'roll_no': 'رقم القيد',
      'phone_number': 'رقم الهاتف',
      'class_grade': 'الصف / المرحلة',
      'shift': 'الفترة',
      'morning': 'صباحاً',
      'evening': 'مساءً',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'teacher_name': 'اسم المعلم',
      'notice_channel': 'وسيلة الإشعارات',
      'message_language': 'لغة الرسالة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'fee_record': 'سجل الرسوم',
      'fee_amount': 'مبلغ الرسوم',
      'select_month': 'اختر الشهر',
      'fee_status': 'حالة الرسوم',
      'due': 'مستحق',
      'partially_paid': 'مدفوع جزئياً',
      'paid': 'مدفوع بالكامل',
      'attendance': 'التحضير',
      'present': 'حاضر',
      'absent': 'غائب',
      'leave': 'إجازة',
      'sabaq_lessons': 'متابعة الدروس',
      'total_students': 'إجمالي الطلاب',
      'apply_to_all': 'تطبيق على الكل',
      'change_teacher': 'تغيير اسم المعلم',
      'change_topic': 'تغيير موضوع اليوم',
      'book_name': 'اسم الكتاب',
      'lesson_surah': 'الدرس / السورة',
      'total': 'الإجمالي',
      'collected': 'المحصلة',
      'actions': 'الإجراءات',
      'select_language': 'اختر اللغة',
      'urdu': 'أردو (اردو)',
      'english': 'الإنجليزية (English)',
      'arabic': 'العربية',
      'hindi': 'الهندية (हिंदी)',
      'telugu': 'التيلوغو (తెలుగు)',
      'kannada': 'الكانادية (ಕನ್ನಡ)',
      'tamil': 'التاميلية (தமிழ்)',
      'malayalam': 'المالايالامية (മലയാളം)',
      'no_students_found': 'لم يتم العثور على طلاب',
      'confirm_delete': 'هل أنت تأكد من حذف هذا الطالب؟',
      'view_sabaq': 'عرض الدرس',
      'call': 'اتصال',
      'whatsapp': 'واتساب',
      'all': 'الكل',
      'analytics': 'التحليلات والتقارير',
      'theme_mode': 'تغيير المظهر',
      'print_pdf': 'طباعة PDF',
      'fee_receipt': 'إيصال الرسوم',
      'report_card': 'التقرير الدراسي',
      'consecutive_absent_alert': 'تنبيه الغياب المتكرر',
      'consecutive_absent_desc': 'هؤلاء الطلاب غائبون لأكثر من 3 أيام متتالية',
      'total_due_amount': 'إجمالي المبلغ المستحق',
      'total_paid_amount': 'إجمالي المبلغ المدفوع',
      'attendance_rate': 'نسبة الحضور',
      'select_role': 'اختر دورك',
      'full_name': 'الاسم الكامل',
      'pin': 'رمز PIN',
      'confirm_pin': 'تأكيد رمز PIN',
      'welcome': 'أهلاً وسهلاً',
      'continue_btn': 'متابعة',
      'login': 'تسجيل الدخول',
      'new_admission': 'قبول جديد',
      'old_admission': 'طالب سابق',
      'advanced_dashboard': 'لوحة التحكم المتقدمة',
      'staff_logins': 'إدارة حسابات الموظفين',
      'parent_logins': 'إدارة حسابات أولياء الأمور',
      'create_group': 'إنشاء مجموعة أو صف',
      'attendance_ledger': 'سجل الحضور',
      'lesson_plan': 'خطة الدروس',
      'student_name': 'اسم الطالب',
      'father_name': 'اسم الوالد/الوصي',
      'father_phone': 'رقم هاتف الوالد/الوصي',
      'admission_date': 'تاريخ القبول',
      'batch_group': 'مجموعة الدفعة',
      'shift_timing': 'توقيت الوردية',
      'overview': 'نظرة عامة',
      'quick_actions': 'إجراءات سريعة',
      'mark_attendance': 'تسجيل الحضور',
      'fee_portal': 'بوابة الرسوم',
      'community_chat': 'المجتمع والمراسلة',
      'results_performance': 'النتائج والأداء',
      'admin_control': 'بوابة تحكم المشرف',
      'leave_portal': 'بوابة الإجازات',
      'fee_collection': 'تحصيل الرسوم',
      'attendance_result': 'نتيجة الحضور',
      'madrasa_title': 'المدرسة أيه إي بي',
      'select_subject': 'اختر الموضوع',
      'lesson_entry_title': 'إدخال الدرس (تحدث أو اكتب)',
      'dars_entry_title': 'إدخال الدرس (في الفصل)',
      'save_all_entries': 'حفظ جميع المدخلات',
      'save_as_pdf': 'حفظ بصيغة PDF',
      'mark_all_yaad_hai': 'تحديد الكل كمحفوظ',
      'mark_all_iaadah': 'تحديد الكل كإعادة',
      'id_card': 'بطاقة الهوية',
      'promote': 'ترقية الفصل',
      'certificate': 'شهادة المغادرة',
      'maktab_rules': 'قواعد المكتب',
      'permissions': 'الصلاحيات',
      'db_import_export': 'نسخ قاعدة البيانات واستعادتها',
      'security_logins': 'إدارة الأمن وتسجيل الدخول',
      'student_academic_controls': 'ضوابط الطلاب والأكاديمية',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'hi': {
      'app_title': 'मकतब मैनेजर',
      'late': 'विलंब',
      'select': 'चुनें',
      'cap_uniform_books': 'टोपी / यूनिफॉर्म / पुस्तकें',
      'late_arrival': 'देर से आया',
      'attendance_tap': 'उपस्थिति\n(टैप करें)',
      'student_father_header': 'छात्र का नाम\nपिता का नाम',
      'notifications_center': 'सूचना केंद्र',
      'prev_attendance_saved': 'पिछली उपस्थिति सफलतापूर्वक सहेजी गई।',
      'new_admin_msg': 'एडमिन से नया संदेश प्राप्त हुआ।',
      'student_attendance_list': 'छात्र उपस्थिति सूची',
      'hardware_test_tool': 'हार्डवेयर डायग्नोस्टिक टूल्स (माइक और कैमरा)',
      'mic_test_title': 'माइक और वॉयस रिकग्निशन टेस्ट',
      'camera_test_title': 'कैमरा फोटो कैप्चर टेस्ट',
      'test_mic_btn': 'माइक टेस्ट करें',
      'test_camera_btn': 'कैमरा टेस्ट करें',
      'close': 'बंद करें',
      'students_list': 'छात्र सूची',
      'add_student': 'नया छात्र जोड़ें',
      'edit_student': 'छात्र विवरण संपादित करें',
      'delete_student': 'हटाएं',
      'search_hint': 'नाम, रोल नंबर या पिता के नाम से खोजें...',
      'name': 'नाम',
      'roll_no': 'रोल नंबर',
      'phone_number': 'फ़ोन नंबर',
      'class_grade': 'कक्षा / दर्जा',
      'shift': 'शिफ्ट',
      'morning': 'सुबह',
      'evening': 'शाम',
      'gender': 'लिंग',
      'male': 'लड़का',
      'female': 'लड़की',
      'teacher_name': 'शिक्षक का नाम',
      'notice_channel': 'सूचना का तरीका',
      'message_language': 'संदेश की भाषा',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'fee_record': 'फीस रिकॉर्ड',
      'fee_amount': 'फीस राशि',
      'select_month': 'महीना चुनें',
      'fee_status': 'फीस की स्थिति',
      'due': 'बकाया',
      'partially_paid': 'आंशिक भुगतान',
      'paid': 'भुगतान हो गया',
      'attendance': 'उपस्थिति',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'leave': 'छुट्टी',
      'sabaq_lessons': 'पाठ लक्ष्य',
      'total_students': 'कुल छात्र',
      'apply_to_all': 'सभी पर लागू करें',
      'change_teacher': 'शिक्षक का नाम बदलें',
      'change_topic': 'आज का विषय बदलें',
      'book_name': 'पुस्तक का नाम',
      'lesson_surah': 'पाठ / सूरा',
      'total': 'कुल',
      'collected': 'वसूल किया गया',
      'actions': 'कार्रवाई',
      'select_language': 'भाषा चुनें',
      'urdu': 'उर्दू (اردو)',
      'english': 'अंग्रेज़ी (English)',
      'arabic': 'अरबी (العربية)',
      'hindi': 'हिंदी',
      'telugu': 'तेलुगु (తెలుగు)',
      'kannada': 'कन्नड़ (ಕನ್ನಡ)',
      'tamil': 'तमिल (தமிழ்)',
      'malayalam': 'मलयालम (മലയാളം)',
      'no_students_found': 'कोई छात्र नहीं मिला',
      'confirm_delete': 'क्या आप वाकई इस छात्र को हटाना चाहते हैं?',
      'view_sabaq': 'पाठ देखें',
      'call': 'कॉल करें',
      'whatsapp': 'WhatsApp',
      'all': 'सभी',
      'analytics': 'विश्लेषण और रिपोर्ट',
      'theme_mode': 'थीम बदलें',
      'print_pdf': 'PDF प्रिंट करें',
      'fee_receipt': 'फीस रसीद',
      'report_card': 'रिपोर्ट कार्ड',
      'consecutive_absent_alert': 'लगातार अनुपस्थिति अलर्ट',
      'consecutive_absent_desc': 'ये छात्र लगातार 3+ दिनों से अनुपस्थित हैं',
      'total_due_amount': 'कुल बकाया राशि',
      'total_paid_amount': 'कुल भुगतान राशि',
      'attendance_rate': 'उपस्थिति दर',
      'select_role': 'अपनी भूमिका चुनें',
      'full_name': 'पूरा नाम',
      'pin': 'पिन (PIN)',
      'confirm_pin': 'पिन की पुष्टि करें',
      'welcome': 'स्वागत है',
      'continue_btn': 'जारी रखें',
      'login': 'लॉग इन करें',
      'new_admission': 'नया प्रवेश',
      'old_admission': 'पुराना छात्र',
      'advanced_dashboard': 'एडवांस डैशबोर्ड',
      'staff_logins': 'स्टाफ लॉगिन प्रबंधन',
      'parent_logins': 'अभिभावक लॉगिन प्रबंधन',
      'create_group': 'क्लास/ग्रुप बनाएं',
      'attendance_ledger': 'उपस्थिति रजिस्टर',
      'lesson_plan': 'पाठ योजना',
      'student_name': 'छात्र का नाम',
      'father_name': 'माता-पिता/अभिभावक का नाम',
      'father_phone': 'माता-पिता/अभिभावक का फोन',
      'admission_date': 'प्रवेश तिथि',
      'batch_group': 'बैच समूह',
      'shift_timing': 'शिफ्ट का समय',
      'overview': 'सारांश',
      'quick_actions': 'त्वरित कार्रवाई',
      'mark_attendance': 'हाज़िरी दर्ज करें',
      'fee_portal': 'फीस पोर्टल',
      'community_chat': 'समुदाय चैट',
      'results_performance': 'परिणाम और प्रदर्शन',
      'admin_control': 'एडमिन कंट्रोल पोर्टल',
      'leave_portal': 'छुट्टी पोर्टल',
      'fee_collection': 'फीस वसूली',
      'attendance_result': 'हाज़िरी का परिणाम',
      'madrasa_title': 'मदरसा एआईबी',
      'select_subject': 'विषय चुनें',
      'lesson_entry_title': 'सबक प्रविष्टि (बोलें या लिखें)',
      'dars_entry_title': 'दर्स प्रविष्टि (कक्षा में)',
      'save_all_entries': 'सभी प्रविष्टियाँ सहेजें',
      'save_as_pdf': 'पीडीएफ के रूप में सहेजें',
      'mark_all_yaad_hai': 'सभी याद हैं चिह्नित करें',
      'mark_all_iaadah': 'सभी दोहराव चिह्नित करें',
      'id_card': 'पहचान पत्र',
      'promote': 'कक्षा पदोन्नति',
      'certificate': 'स्थानांतरण प्रमाणपत्र',
      'maktab_rules': 'मकतब नियम',
      'permissions': 'अनुमतियाँ',
      'db_import_export': 'डेटाबेस बैकअप और पुनर्स्थापना',
      'security_logins': 'सुरक्षा और लॉगिन प्रबंधन',
      'student_academic_controls': 'छात्र और शैक्षणिक नियंत्रण',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'te': {
      'app_title': 'మక్తబ్ మేనేజర్',
      'late': 'ఆలస్యం',
      'select': 'ఎంచుకోండి',
      'cap_uniform_books': 'టోపీ / యూనిఫాం / పుస్తకాలు',
      'late_arrival': 'ఆలస్యంగా వచ్చారు',
      'attendance_tap': 'హాజరు\n(నొక్కండి)',
      'student_father_header': 'విద్యార్థి పేరు\nతండ్రి పేరు',
      'notifications_center': 'నోటిఫికేషన్ కేంద్రం',
      'prev_attendance_saved': 'మునుపటి హాజరు విజయవంతంగా సేవ్ చేయబడింది.',
      'new_admin_msg': 'అడ్మిన్ నుండి కొత్త సందేశం వచ్చింది.',
      'student_attendance_list': 'విద్యార్థి హాజరు జాబితా',
      'hardware_test_tool': 'హార్డ్‌వేర్ డయాగ్నోస్టిక్ టూల్స్ (మైక్ & కెమెరా)',
      'mic_test_title': 'మైక్రోఫోన్ స్పీచ్-టు-టెక్స్ట్ టెస్ట్',
      'camera_test_title': 'కెమెరా క్యాప్చర్ టెస్ట్',
      'test_mic_btn': 'మైక్ టెస్ట్ చేయండి',
      'test_camera_btn': 'కెమెరా టెస్ట్ చేయండి',
      'close': 'మూసివేయి',
      'students_list': 'విద్యార్థుల జాబితా',
      'add_student': 'కొత్త విద్యార్థిని జోడించండి',
      'edit_student': 'విద్యార్థి వివరాలను సవరించండి',
      'delete_student': 'తొలగించండి',
      'search_hint': 'పేరు, రోల్ నం, లేదా తండ్రి పేరు ద్వారా శోధించండి...',
      'name': 'పేరు',
      'roll_no': 'రోల్ నంబర్',
      'phone_number': 'ఫోన్ నంబర్',
      'class_grade': 'తరగతి / గ్రేడ్',
      'shift': 'షిఫ్ట్',
      'morning': 'ఉదయం',
      'evening': 'సాయంత్రం',
      'gender': 'లింగం',
      'male': 'మగ',
      'female': 'ఆడ',
      'teacher_name': 'ఉపాధ్యాయుని పేరు',
      'notice_channel': 'నోటీస్ పద్ధతి',
      'message_language': 'సందేశ భాష',
      'save': 'సేవ్ చేయండి',
      'cancel': 'రద్దు చేయండి',
      'delete': 'తొలగించు',
      'fee_record': 'ఫీజు రికార్డు',
      'fee_amount': 'ఫీజు మొత్తం',
      'select_month': 'నెలను ఎంచుకోండి',
      'fee_status': 'ఫీజు స్థితి',
      'due': 'బాకీ',
      'partially_paid': 'పాక్షికంగా చెల్లించారు',
      'paid': 'పూర్తిగా చెల్లించారు',
      'attendance': 'హాజరు',
      'present': 'హాజరు',
      'absent': 'గైర్హాజరు',
      'leave': 'సెలవు',
      'sabaq_lessons': 'పాఠం లక్ష్యం',
      'total_students': 'మొత్తం విద్యార్థులు',
      'apply_to_all': 'అందరికీ వర్తింపజేయండి',
      'change_teacher': 'ఉపాధ్యాయుల పేరు మార్చండి',
      'change_topic': 'ఈరోజు విషయాన్ని మార్చండి',
      'book_name': 'పుస్తకం పేరు',
      'lesson_surah': 'పాఠం / సూరా',
      'total': 'మొత్తం',
      'collected': 'వసూలు చేయబడింది',
      'actions': 'చర్యలు',
      'select_language': 'భాష ఎంచుకోండి',
      'urdu': 'ఉర్దూ (اردو)',
      'english': 'ఇంగ్లీషు (English)',
      'arabic': 'అరబిక్ (العربية)',
      'hindi': 'హిందీ (हिंदी)',
      'telugu': 'తెలుగు',
      'kannada': 'కన్నడ (ಕನ್ನಡ)',
      'tamil': 'తమిళం (தமிழ்)',
      'malayalam': 'మలయాళం (മലയാളം)',
      'no_students_found': 'విద్యార్థులు కనుగొనబడలేదు',
      'confirm_delete': 'మీరు నిజంగా ఈ విద్యార్థిని తొలగించాలనుకుంటున్నారా?',
      'view_sabaq': 'పాఠం చూడండి',
      'call': 'కాల్ చేయండి',
      'whatsapp': 'WhatsApp',
      'all': 'అన్నీ',
      'analytics': 'విశ్లేషణలు & నివేదికలు',
      'theme_mode': 'థీమ్ మార్చండి',
      'print_pdf': 'PDF ప్రింట్ చేయండి',
      'fee_receipt': 'ఫీజు రసీదు',
      'report_card': 'రిపోర్ట్ కార్డ్',
      'consecutive_absent_alert': 'వరుస గైర్హాజరు హెచ్చరిక',
      'consecutive_absent_desc': 'ఈ విద్యార్థులు వరుసగా 3+ రోజులు గైర్హాజరు అయ్యారు',
      'total_due_amount': 'మొత్తం బాకీ మొత్తం',
      'total_paid_amount': 'మొత్తం చెల్లించిన మొత్తం',
      'attendance_rate': 'హాజరు రేటు',
      'select_role': 'మీ పాత్రను ఎంచుకోండి',
      'full_name': 'పూర్తి పేరు',
      'pin': 'పిన్ (PIN)',
      'confirm_pin': 'పిన్ ధృవీకరించండి',
      'welcome': 'స్వాగతం',
      'continue_btn': 'కొనసాగించండి',
      'login': 'లాగిన్',
      'new_admission': 'కొత్త ప్రవేశం',
      'old_admission': 'పాత విద్యార్థి',
      'advanced_dashboard': 'అడ్వాన్స్డ్ డాష్‌బోర్డ్',
      'staff_logins': 'స్టాఫ్ లాగిన్ నిర్వహణ',
      'parent_logins': 'తల్లిదండ్రుల లాగిన్ నిర్వహణ',
      'create_group': 'గ్రూప్ సృష్టించండి',
      'attendance_ledger': 'హాజరు రికార్డు',
      'lesson_plan': 'పాఠ్య ప్రణాళిక',
      'student_name': 'విద్యార్థి పేరు',
      'father_name': 'తల్లిదండ్రులు/సంరక్షకుల పేరు',
      'father_phone': 'తల్లిదండ్రులు/సంరక్షకుల ఫోన్',
      'admission_date': 'ప్రవేశ తేదీ',
      'batch_group': 'బ్యాచ్ గ్రూప్',
      'shift_timing': 'షిఫ్ట్ సమయం',
      'overview': 'అవలోకనం',
      'quick_actions': 'త్వరిత చర్యలు',
      'mark_attendance': 'హాజరు నమోదు చేయండి',
      'fee_portal': 'ఫీజు పోర్టల్',
      'community_chat': 'సమాజ చాట్',
      'results_performance': 'ఫలితాలు & పనితీరు',
      'admin_control': 'అడ్మిన్ కంట్రోల్ పోర్టల్',
      'leave_portal': 'సెలవు పోర్టల్',
      'fee_collection': 'ఫీజు వసూలు',
      'attendance_result': 'హారజు ఫలితం',
      'madrasa_title': 'మదరసా ఏఐబీ',
      'select_subject': 'సబ్జెక్ట్ ఎంచుకోండి',
      'lesson_entry_title': 'పాఠం నమోదు (మాట్లాడండి లేదా టైప్ చేయండి)',
      'dars_entry_title': 'దర్స్ నమోదు (తరగతిలో)',
      'save_all_entries': 'అన్ని నమోదులను సేవ్ చేయండి',
      'save_as_pdf': 'PDFగా సేవ్ చేయండి',
      'mark_all_yaad_hai': 'అన్ని గుర్తుంచుకోబడ్డాయిగా గుర్తించండి',
      'mark_all_iaadah': 'అన్ని పునశ్చరణగా గుర్తించండి',
      'id_card': 'ఐడెంటిటీ కార్డ్',
      'promote': 'తరగతి ప్రమోషన్',
      'certificate': 'బదిలీ ధృవీకరణ పత్రం',
      'maktab_rules': 'మక్తబ్ నియమాలు',
      'permissions': 'అనుమతులు',
      'db_import_export': 'డేటాబేస్ బ్యాకప్ & పునరుద్ధరణ',
      'security_logins': 'భద్రత & లాగిన్ నిర్వహణ',
      'student_academic_controls': 'విద్యార్థి & విద్యా నియంత్రణలు',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'kn': {
      'app_title': 'ಮಕ್ತಬ್ ಮ್ಯಾನೇಜರ್',
      'late': 'ವಿಳಂಬ',
      'select': 'ಆರಿಸಿ',
      'cap_uniform_books': 'ಟೋಪಿ / ಯುನಿಫಾರ್ಮ್ / ಪುಸ್ತಕಗಳು',
      'late_arrival': 'ತಡವಾಗಿ ಬಂದರು',
      'attendance_tap': 'ಹಾಜರಾತಿ\n(ಟ್ಯಾಪ್ ಮಾಡಿ)',
      'student_father_header': 'ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು\nತಂದೆಯ ಹೆಸರು',
      'notifications_center': 'ಸೂಚನಾ ಕೇಂದ್ರ',
      'prev_attendance_saved': 'ಹಿಂದಿನ ಹಾಜರಾತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ.',
      'new_admin_msg': 'ಅಡ್ಮಿನ್‌ನಿಂದ പുതിയ ಸಂದೇಶ ಸ್ವೀಕರಿಸಲಾಗಿದೆ.',
      'student_attendance_list': 'ವಿದ್ಯಾರ್ಥಿಗಳ ಹಾಜರಾತಿ ಪಟ್ಟಿ',
      'hardware_test_tool': 'ಹಾರ್ಡ್‌ವೇರ್ ಡೈಾಗ್ನೋಸ್ಟಿಕ್ ಉಪಕರಣಗಳು (ಮೈಕ್ ಮತ್ತು ಕ್ಯಾಮೆರಾ)',
      'mic_test_title': 'ಮೈಕ್ರೋಫೋನ್ ಸ್ಪೀಚ್-ಟು-ಟೆಕ್ಸ್ಟ್ ಪರೀಕ್ಷೆ',
      'camera_test_title': 'ಕ್ಯಾಮೆರಾ ಕ್ಯಾಪ್ಚರ್ ಪರೀಕ್ಷೆ',
      'test_mic_btn': 'ಮೈಕ್ ಪರೀಕ್ಷಿಸಿ',
      'test_camera_btn': 'ಕ್ಯಾಮೆರಾ ಪರೀಕ್ಷಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'students_list': 'ವಿದ್ಯಾರ್ಥಿ ಪಟ್ಟಿ',
      'add_student': 'ಹೊಸ ವಿದ್ಯಾರ್ಥಿ ಸೇರಿಸಿ',
      'edit_student': 'ವಿದ್ಯಾರ್ಥಿ ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ',
      'delete_student': 'ಅಳಿಸಿ',
      'search_hint': 'ಹೆಸರು, ರೋಲ್ ನಂ, ಅಥವಾ ತಂದೆ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ...',
      'name': 'ಹೆಸರು',
      'roll_no': 'ರೋಲ್ ಸಂಖ್ಯೆ',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'class_grade': 'ತರಗತಿ / ಗ್ರೇಡ್',
      'shift': 'ಶಿಫ್ಟ್',
      'morning': 'ಬೆಳಗ್ಗೆ',
      'evening': 'ಸಂಜೆ',
      'gender': 'ಲಿಂಗ',
      'male': 'ಗಂಡು',
      'female': 'ಹೆಣ್ಣು',
      'teacher_name': 'ಶಿಕ್ಷಕರ ಹೆಸರು',
      'notice_channel': 'ಸೂಚನೆ ವಿಧಾನ',
      'message_language': 'ಸಂದೇಶ ಭಾಷೆ',
      'save': 'ಉಳಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'delete': 'ಅಳಿಸಿ',
      'fee_record': 'ಶುಲ್ಕ ದಾಖಲೆ',
      'fee_amount': 'ಶುಲ್ಕ ಮೊತ್ತ',
      'select_month': 'ತಿಂಗಳು ಆಯ್ಕೆಮಾಡಿ',
      'fee_status': 'ಶುಲ್ಕ ಸ್ಥಿತಿ',
      'due': 'ಬಾಕಿ',
      'partially_paid': 'ಭಾಗಶಃ ಪಾವತಿ',
      'paid': 'ಸಂಪೂರ್ಣ ಪಾವತಿ ಆಗಿದೆ',
      'attendance': 'ಹಾಜರಾತಿ',
      'present': 'ಹಾಜರು',
      'absent': 'ಗೈರುಹಾಜರು',
      'leave': 'ರಜೆ',
      'sabaq_lessons': 'ಪಾಠ ಗುರಿ',
      'total_students': 'ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು',
      'apply_to_all': 'ಎಲ್ಲರಿಗೂ ಅನ್ವಯಿಸಿ',
      'change_teacher': 'ಶಿಕ್ಷಕರ ಹೆಸರನ್ನು ಬದಲಾಯಿಸಿ',
      'change_topic': 'ಇಂದಿನ ವಿಷಯವನ್ನು ಬದಲಾಯಿಸಿ',
      'book_name': 'ಪುಸ್ತಕದ ಹೆಸರು',
      'lesson_surah': 'ಪಾಠ / ಸೂರಾ',
      'total': 'ಒಟ್ಟು',
      'collected': 'ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
      'actions': 'ಕ್ರಿಯೆಗಳು',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'urdu': 'ಉರ್ದು (اردو)',
      'english': 'ಇಂಗ್ಲಿಷ್ (English)',
      'arabic': 'ಅರಬಿಕ್ (العربية)',
      'hindi': 'ಹಿಂದಿ (हिंदी)',
      'telugu': 'ತೆಲುಗು (తెలుగు)',
      'kannada': 'ಕನ್ನಡ',
      'tamil': 'ತಮಿಳು (தமிழ்)',
      'malayalam': 'ಮಲಯಾಳಂ (മലയാളം)',
      'no_students_found': 'ವಿದ್ಯಾರ್ಥಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'confirm_delete': 'ನೀವು ನಿಜವಾಗಿಯೂ ಈ ವಿದ್ಯಾರ್ಥಿಯನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
      'view_sabaq': 'ಪಾಠ ನೋಡಿ',
      'call': 'ಕರೆ ಮಾಡಿ',
      'whatsapp': 'WhatsApp',
      'all': 'ಎಲ್ಲಾ',
      'analytics': 'ವಿಶ್ಲೇಷಣೆ & ವರದಿಗಳು',
      'theme_mode': 'ಥೀಮ್ ಬದಲಾಯಿಸಿ',
      'print_pdf': 'PDF ಮುದ್ರಿಸಿ',
      'fee_receipt': 'ಶುಲ್ಕ ರಸೀದಿ',
      'report_card': 'ವರದಿ ಕಾರ್ಡ್',
      'consecutive_absent_alert': 'ಸತತ ಗೈರುಹಾಜರು ಎಚ್ಚರಿಕೆ',
      'consecutive_absent_desc': 'ಈ ವಿದ್ಯಾರ್ಥಿಗಳು ಸತತ 3+ ದಿನಗಳಿಂದ ಗೈರುಹಾಜರಾಗಿದ್ದಾರೆ',
      'total_due_amount': 'ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ',
      'total_paid_amount': 'ಒಟ್ಟು ಪಾವತಿ ಮೊತ್ತ',
      'attendance_rate': 'ಹಾಜರಾತಿ ದರ',
      'select_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'pin': 'ಪಿನ್ (PIN)',
      'confirm_pin': 'ಪಿನ್ ದೃಢೀಕರಿಸಿ',
      'welcome': 'ಸ್ವಾಗತ',
      'continue_btn': 'ಮುಂದುವರಿಸಿ',
      'login': 'ಲಾಗಿನ್',
      'new_admission': 'ಹೊಸ ಪ್ರವೇಶ',
      'old_admission': 'ಹಳೆಯ ವಿದ್ಯಾರ್ಥಿ',
      'advanced_dashboard': 'ಅಡ್ವಾನ್ಸ್ಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'staff_logins': 'ಸಿಬ್ಬಂದಿ ಲಾಗಿನ್ ನಿರ್ವಹಣೆ',
      'parent_logins': 'ಪೋಷಕರ ಲಾಗಿನ್ ನಿರ್ವಹಣೆ',
      'create_group': 'ಗುಂಪು ರಚಿಸಿ',
      'attendance_ledger': 'ಹಾಜರಾತಿ ಪುಸ್ತಕ',
      'lesson_plan': 'ಪಾಠ ಯೋಜನೆ',
      'student_name': 'ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು',
      'father_name': 'ಪೋಷಕರು/ರಕ್ಷಕರ ಹೆಸರು',
      'father_phone': 'ಪೋಷಕರು/ರಕ್ಷಕರ ಫೋನ್',
      'admission_date': 'ಪ್ರವೇಶ ದಿನಾಂక',
      'batch_group': 'ಬ್ಯಾಚ್ ಗುಂಪು',
      'shift_timing': 'ಶಿಫ್ಟ್ ಸಮಯ',
      'overview': 'ಅವಲೋಕನ',
      'quick_actions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
      'mark_attendance': 'ಹಾಜರಾತಿ ನಮೂದಿಸಿ',
      'fee_portal': 'ಶುಲ್ಕ ಪೋರ್ಟಲ್',
      'community_chat': 'ಸಮುದಾಯ ಚಾಟ್',
      'results_performance': 'ಫಲಿತಾಂಶ ಮತ್ತು ಪ್ರದರ್ಶನ',
      'admin_control': 'ಅಡ್ಮಿನ್ ಕಂಟ್ರೋಲ್ ಪೋರ್ಟಲ್',
      'leave_portal': 'ರಜೆ ಪೋರ್ಟಲ್',
      'fee_collection': 'ಶುಲ್ಕ ಸಂಗ್ರಹ',
      'attendance_result': 'ಹಾಜರಾತಿ ಫಲಿತಾಂಶ',
      'madrasa_title': 'ಮದರಸಾ ಎಐಬಿ',
      'select_subject': 'ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ',
      'lesson_entry_title': 'ಪಾಠ ನಮೂದು (ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ)',
      'dars_entry_title': 'ದರ್ಸ್ ನಮೂದು (ತರಗತಿಯಲ್ಲಿ)',
      'save_all_entries': 'ಎಲ್ಲಾ ನಮೂದುಗಳನ್ನು ಉಳಿಸಿ',
      'save_as_pdf': 'PDF ಆಗಿ ಉಳಿಸಿ',
      'mark_all_yaad_hai': 'ಎಲ್ಲಾ ನೆನಪಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      'mark_all_iaadah': 'ಎಲ್ಲಾ ಪುನರಾವರ್ತನೆ ಎಂದು ಗುರುತಿಸಿ',
      'id_card': 'ಗುರುತಿನ ಚೀಟಿ',
      'promote': 'ತರಗತಿ ಬಡ್ತಿ',
      'certificate': 'ವರ್ಗಾವಣೆ ಪ್ರಮಾಣಪತ್ರ',
      'maktab_rules': 'ಮಕ್ತಬ್ ನಿಯಮಗಳು',
      'permissions': 'ಅನುಮತಿಗಳು',
      'db_import_export': 'ಡೇಟಾಬೇಸ್ ಬ್ಯಾಕಪ್ ಮತ್ತು ಮರುಸ್ಥಾಪನೆ',
      'security_logins': 'ಭದ್ರತೆ ಮತ್ತು ಲಾಗಿನ್ ನಿರ್ವಹಣೆ',
      'student_academic_controls': 'ವಿದ್ಯಾರ್ಥಿ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ನಿಯಂತ್ರಣಗಳು',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'ta': {
      'app_title': 'மக்தப் மேலாளர்',
      'late': 'தாமதம்',
      'select': 'தேர்ந்தெடு',
      'cap_uniform_books': 'தொப்பி / சீருடை / புத்தகங்கள்',
      'late_arrival': 'தாமதமாக வந்தார்',
      'attendance_tap': 'வருகை\n(தட்டவும்)',
      'student_father_header': 'மாணவர் பெயர்\nதந்தையின் பெயர்',
      'notifications_center': 'அறிவிப்பு மையம்',
      'prev_attendance_saved': 'முந்தைய வருகை வெற்றிகரமாக சேமிக்கப்பட்டது.',
      'new_admin_msg': 'நிர்வாகியிடமிருந்து புதிய செய்தி வந்தது.',
      'student_attendance_list': 'மாணவர் வருகைப் பட்டியல்',
      'hardware_test_tool': 'வன்பொருள் கண்டறிதல் கருவிகள் (மைக் & கேமரா)',
      'mic_test_title': 'மைக்ரோஃபோன் பேச்சிலிருந்து உரை சோதனை',
      'camera_test_title': 'கேமரா பிடிப்பு சோதனை',
      'test_mic_btn': 'மைக்கை சோதிக்கவும்',
      'test_camera_btn': 'கேமராவை சோதிக்கவும்',
      'close': 'மூடு',
      'students_list': 'மாணவர் பட்டியல்',
      'add_student': 'புதிய மாணவரை சேர்க்கவும்',
      'edit_student': 'மாணவர் விவரங்களை திருத்தவும்',
      'delete_student': 'நீக்கு',
      'search_hint': 'பெயர், சுருட்டு எண், அல்லது தந்தை பெயரால் தேடுங்கள்...',
      'name': 'பெயர்',
      'roll_no': 'சுருட்டு எண்',
      'phone_number': 'தொலைபேசி எண்',
      'class_grade': 'வகுப்பு / தரம்',
      'shift': 'ஷிஃப்ட்',
      'morning': 'காலை',
      'evening': 'மாலை',
      'gender': 'பாலினம்',
      'male': 'ஆண்',
      'female': 'பெண்',
      'teacher_name': 'ஆசிரியர் பெயர்',
      'notice_channel': 'அறிவிப்பு முறை',
      'message_language': 'செய்தி மொழி',
      'save': 'சேமிக்கவும்',
      'cancel': 'ரத்து செய்',
      'delete': 'நீக்கு',
      'fee_record': 'கட்டண பதிவு',
      'fee_amount': 'கட்டண தொகை',
      'select_month': 'மாதத்தை தேர்ந்தெடுக்கவும்',
      'fee_status': 'கட்டண நிலை',
      'due': 'நிலுவை',
      'partially_paid': 'பகுதியாக செலுத்தப்பட்டது',
      'paid': 'முழுமையாக செலுத்தப்பட்டது',
      'attendance': 'வருகை',
      'present': 'வருகை',
      'absent': 'வருகையில்லை',
      'leave': 'விடுப்பு',
      'sabaq_lessons': 'பாட இலக்கு',
      'total_students': 'மொத்த மாணவர்கள்',
      'apply_to_all': 'அனைவருக்கும் பயன்படுத்துக',
      'change_teacher': 'ஆசிரியர் பெயரை மாற்றவும்',
      'change_topic': 'இன்றைய தலைப்பை மாற்றவும்',
      'book_name': 'புத்தகத்தின் பெயர்',
      'lesson_surah': 'பாடம் / சூரா',
      'total': 'மொத்தம்',
      'collected': 'வசூலிக்கப்பட்டது',
      'actions': 'செயல்கள்',
      'select_language': 'மொழியை தேர்ந்தெடுக்கவும்',
      'urdu': 'உருது (اردو)',
      'english': 'ஆங்கிலம் (English)',
      'arabic': 'அரபிக் (العربية)',
      'hindi': 'இந்தி (हिंदी)',
      'telugu': 'தெலுங்கு (తెలుగు)',
      'kannada': 'கன்னடம் (<ctrl42><ctrl42><ctrl42>)',
      'tamil': 'தமிழ்',
      'malayalam': 'மலையாளம் (മലയാളം)',
      'no_students_found': 'மாணவர்கள் எவரும் கண்டுபிடிக்கப்படவில்லை',
      'confirm_delete': 'இந்த மாணவரை நீக்க விரும்புகிறீர்களா?',
      'view_sabaq': 'பாடத்தை பாருங்கள்',
      'call': 'அழையுங்கள்',
      'whatsapp': 'WhatsApp',
      'all': 'அனைத்தும்',
      'analytics': 'பகுப்பாய்வு & அறிக்கைகள்',
      'theme_mode': 'தீம் மாற்று',
      'print_pdf': 'PDF அச்சிடு',
      'fee_receipt': 'கட்டண ரசீது',
      'report_card': 'அறிக்கை அட்டை',
      'consecutive_absent_alert': 'தொடர் வருகையில்லா எச்சரிக்கை',
      'consecutive_absent_desc': 'இந்த மாணவர்கள் தொடர்ச்சியாக 3+ நாட்கள் வருகையில்லாமல் உள்ளனர்',
      'total_due_amount': 'மொத்த நிலுவை தொகை',
      'total_paid_amount': 'மொத்த செலுத்திய தொகை',
      'attendance_rate': 'வருகை விகிதம்',
      'select_role': 'உங்கள் பாத்திரத்தை தேர்ந்தெடுக்கவும்',
      'full_name': 'முழு பெயர்',
      'pin': 'பின் (PIN)',
      'confirm_pin': 'பினை உறுதிப்படுத்தவும்',
      'welcome': 'வரவேற்பு',
      'continue_btn': 'தொடரவும்',
      'login': 'உள்நுழை',
      'new_admission': 'புதிய சேர்க்கை',
      'old_admission': 'பழைய மாணவர்',
      'advanced_dashboard': 'மேம்பட்ட டாஷ்போர்டு',
      'staff_logins': 'ஊழியர் உள்நுழைவு நிர்வாகம்',
      'parent_logins': 'பெற்றோர் உள்நுழைவு நிர்வாகம்',
      'create_group': 'குழுவை உருவாக்கவும்',
      'attendance_ledger': 'வருகை பதிவு',
      'lesson_plan': 'பாடத் திட்டம்',
      'student_name': 'மாணவர் பெயர்',
      'father_name': 'பெற்றோர்/பாதுகாவலர் பெயர்',
      'father_phone': 'பெற்றோர்/பாதுகாவலர் தொலைபேసి',
      'admission_date': 'சேர்க்கை தேதி',
      'batch_group': 'தொகுதி குழு',
      'shift_timing': 'ஷிப்ட் நேரம்',
      'overview': 'கண்ணோட்டம்',
      'quick_actions': 'விரைவு செயல்கள்',
      'mark_attendance': 'வருகையைப் பதிவு செய்யுங்கள்',
      'fee_portal': 'கட்டண போர்ட்டல்',
      'community_chat': 'சமூக அரட்டை',
      'results_performance': 'முடிவுகள் & செயல்திறன்',
      'admin_control': 'நிர்வாக கட்டுப்பாட்டு போர்ட்டல்',
      'leave_portal': 'விடுப்பு போர்ட்டல்',
      'fee_collection': 'கட்டண வசூல்',
      'attendance_result': 'வருகை முடிவு',
      'madrasa_title': 'மதரசா ஏஐபி',
      'select_subject': 'பாடத்தைத் தேர்ந்தெடுக்கவும்',
      'lesson_entry_title': 'பாடம் உள்ளீடு (பேசவும் அல்லது தட்டச்சு செய்யவும்)',
      'dars_entry_title': 'தர்ஸ் உள்ளீடு (வகுப்பில்)',
      'save_all_entries': 'அனைத்து பதிவுகளையும் சேமிக்கவும்',
      'save_as_pdf': 'PDF ஆக சேமிக்கவும்',
      'mark_all_yaad_hai': 'அனைத்தும் நினைவிருக்கிறது என குறிக்கவும்',
      'mark_all_iaadah': 'அனைத்தும் திருப்புதல் என குறிக்கவும்',
      'id_card': 'அடையாள அட்டை',
      'promote': 'வகுப்பு பதவி உயர்வு',
      'certificate': 'மாற்றுச் சான்றிதழ்',
      'maktab_rules': 'மகதப் விதிகள்',
      'permissions': 'அனுமதிகள்',
      'db_import_export': 'தரவுத்தள காப்பு மற்றும் மீட்பு',
      'security_logins': 'பாதுகாப்பு மற்றும் உள்நுழைவு மேலாண்மை',
      'student_academic_controls': 'மாணவர் & கல்வி கட்டுப்பாடுகள்',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  'ml': {
      'app_title': 'മക്തബ് മാനേജർ',
      'late': 'വൈകി',
      'select': 'തിരഞ്ഞെടുക്കുക',
      'cap_uniform_books': 'തൊപ്പി / യൂണിഫോം / പുസ്തകങ്ങൾ',
      'late_arrival': 'വൈകി വന്നു',
      'attendance_tap': 'ഹാജർ\n(ടാപ്പ് ചെയ്യുക)',
      'student_father_header': 'വിദ്യാർത്ഥിയുടെ പേര്\nപിതാവിന്റെ പേര്',
      'notifications_center': 'അറിയിപ്പ് കേന്ദ്രം',
      'prev_attendance_saved': 'മുൻ ഹാജർ വിജയകരമായി സേവ് ചെയ്തു.',
      'new_admin_msg': 'അഡ്മിനിൽ നിന്ന് പുതിയ സന്ദേശം ലഭിച്ചു.',
      'student_attendance_list': 'വിദ്യാർത്ഥി ഹാജർ പട്ടിക',
      'hardware_test_tool': 'ഹാർഡ്‌വെയർ ഡയഗ്നോസ്റ്റിക് ടൂളുകൾ (മൈക്കും ക്യാമറയും)',
      'mic_test_title': 'മൈക്രോഫോൺ സ്പീച്ച്-ടു-ടെക്സ്റ്റ് ടെസ്റ്റ്',
      'camera_test_title': 'ക്യാമറ ക്യാപ്ചർ ടെസ്റ്റ്',
      'test_mic_btn': 'മൈക്ക് ടെസ്റ്റ് ചെയ്യുക',
      'test_camera_btn': 'ക്യാമറ ടെസ്റ്റ് ചെയ്യുക',
      'close': 'അടയ്ക്കുക',
      'students_list': 'വിദ്യാർത്ഥി പട്ടിക',
      'add_student': 'പുതിയ വിദ്യാർത്ഥിയെ ചേർക്കുക',
      'edit_student': 'വിദ്യാർത്ഥി വിവരങ്ങൾ തിരുത്തുക',
      'delete_student': 'ഇല്ലാതാക്കുക',
      'search_hint': 'പേര്, റോൾ നം, അല്ലെങ്കിൽ പിതാവിന്റെ പേര് ഉപയോഗിച്ച് തിരയുക...',
      'name': 'പേര്',
      'roll_no': 'റോൾ നമ്പർ',
      'phone_number': 'ഫോൺ നമ്പർ',
      'class_grade': 'ക്ലാസ് / ഗ്രേഡ്',
      'shift': 'ഷിഫ്റ്റ്',
      'morning': 'രാവിലെ',
      'evening': 'വൈകുന്നേരം',
      'gender': 'ലിംഗം',
      'male': 'ആൺ',
      'female': 'പെൺ',
      'teacher_name': 'അദ്ധ്യാപകന്റെ പേര്',
      'notice_channel': 'അറിയിപ്പ് രീതി',
      'message_language': 'സന്ദേശ ഭാഷ',
      'save': 'സംരക്ഷിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'fee_record': 'ഫീസ് രേഖ',
      'fee_amount': 'ഫീസ് തുക',
      'select_month': 'മാസം തിരഞ്ഞെടുക്കുക',
      'fee_status': 'ഫീസ് നിലവാരം',
      'due': 'കുടിശ്ശിക',
      'partially_paid': 'ഭാഗികമായി അടച്ചു',
      'paid': 'മുഴുവനായി അടച്ചു',
      'attendance': 'ഹാജർ',
      'present': 'ഹാജർ',
      'absent': 'ഗൈർഹാജർ',
      'leave': 'അവധി',
      'sabaq_lessons': 'പാഠ ലക്ഷ്യം',
      'total_students': 'ആകെ വിദ്യാർത്ഥികൾ',
      'apply_to_all': 'എല്ലാവർക്കും ബാധകമാക്കുക',
      'change_teacher': 'അധ്യാപകന്റെ പേര് മാറ്റുക',
      'change_topic': 'ഇന്നത്തെ വിഷയം മാറ്റുക',
      'book_name': 'പുസ്തകത്തിന്റെ പേര്',
      'lesson_surah': 'പാഠം / സൂറ',
      'total': 'ആകെ',
      'collected': 'ശേഖരിച്ചത്',
      'actions': 'നടപടികൾ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'urdu': 'ഉർദു (اردو)',
      'english': 'ഇംഗ്ലീഷ് (English)',
      'arabic': 'അറബിക് (العربية)',
      'hindi': 'ഹിന്ദി (हिंदी)',
      'telugu': 'തെലുഗു (తెలుగు)',
      'kannada': 'കന്നഡ (<ctrl42><ctrl42><ctrl42>)',
      'tamil': 'തമിഴ് (தமிழ்)',
      'malayalam': 'മലയാളം',
      'no_students_found': 'വിദ്യാർത്ഥികളെ കണ്ടെത്താനായില്ല',
      'confirm_delete': 'ഈ വിദ്യാർത്ഥിയെ നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
      'view_sabaq': 'പാഠം കാണുക',
      'call': 'വിളിക്കുക',
      'whatsapp': 'WhatsApp',
      'all': 'എല്ലാം',
      'analytics': 'വിശകലനവും റിപ്പോർട്ടുകളും',
      'theme_mode': 'തീം മാറ്റുക',
      'print_pdf': 'PDF പ്രിന്റ് ചെയ്യുക',
      'fee_receipt': 'ഫീസ് രസീത്',
      'report_card': 'റിപ്പോർട്ട് കാർഡ്',
      'consecutive_absent_alert': 'തുടർച്ചയായ ഗൈർഹാജർ മുന്നറിയിപ്പ്',
      'consecutive_absent_desc': 'ഈ വിദ്യാർത്ഥികൾ തുടർച്ചയായി 3+ ദിവസം ഗൈർഹാജരാണ്',
      'total_due_amount': 'ആകെ കുടിശ്ശിക തുക',
      'total_paid_amount': 'ആകെ അടച്ച തുക',
      'attendance_rate': 'ഹാജർ നിരക്ക്',
      'select_role': 'നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക',
      'full_name': 'പൂർണ്ണ നാമം',
      'pin': 'പിൻ (PIN)',
      'confirm_pin': 'പിൻ സ്ഥിരീകരിക്കുക',
      'welcome': 'സ്വാഗതം',
      'continue_btn': 'തുടരുക',
      'login': 'ലോഗിൻ',
      'new_admission': 'പുതിയ പ്രവേശനം',
      'old_admission': 'പഴയ വിദ്യാർത്ഥി',
      'advanced_dashboard': 'അഡ്വാൻസ്ഡ് ഡാഷ്‌ബോർഡ്',
      'staff_logins': 'സ്റ്റാഫ് ലോഗിൻ മാനേജ്മെന്റ്',
      'parent_logins': 'രക്ഷിതാക്കളുടെ ലോഗിൻ മാനേജ്മെന്റ്',
      'create_group': 'ഗ്രൂപ്പ് സൃഷ്ടിക്കുക',
      'attendance_ledger': 'ഹാജർ രജിസ്റ്റർ',
      'lesson_plan': 'പാഠ പദ്ധതി',
      'student_name': 'വിദ്യാർത്ഥിയുടെ പേര്',
      'father_name': 'രക്ഷാകർത്താവിന്റെ പേര്',
      'father_phone': 'രക്ഷാകർത്താവിന്റെ ഫോൺ',
      'admission_date': 'പ്രവേശന തീയതി',
      'batch_group': 'ബാച്ച് ഗ്രൂപ്പ്',
      'shift_timing': 'ഷിഫ്റ്റ് സമയം',
      'overview': 'അവലോകനം',
      'quick_actions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
      'mark_attendance': 'ഹാജർ രേഖപ്പെടുത്തുക',
      'fee_portal': 'ഫീസ് പോർട്ടൽ',
      'community_chat': 'കമ്മ്യൂണിറ്റി ചാറ്റ്',
      'results_performance': 'ഫലങ്ങളും പ്രകടനവും',
      'admin_control': 'അഡ്മിൻ കൺട്രോൾ പോർട്ടൽ',
      'leave_portal': 'ലീവ് പോർട്ടൽ',
      'fee_collection': 'ഫീസ് ശേഖരണം',
      'attendance_result': 'ഹാജർ ഫലം',
      'madrasa_title': 'മദ്റസ എഐബി',
      'select_subject': 'വിഷയം തിരഞ്ഞെടുക്കുക',
      'lesson_entry_title': 'പാഠം നൽകുക (സംസാരിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക)',
      'dars_entry_title': 'ദർസ് നൽകുക (ക്ലാസ്സിൽ)',
      'save_all_entries': 'എല്ലാ വിവരങ്ങളും സംരക്ഷിക്കുക',
      'save_as_pdf': 'PDF ആയി സംരക്ഷിക്കുക',
      'mark_all_yaad_hai': 'എല്ലാം ഓർമ്മയുണ്ടെന്ന് അടയാളപ്പെടുത്തുക',
      'mark_all_iaadah': 'എല്ലാം ആവർത്തനം എന്ന് അടയാളപ്പെടുത്തുക',
      'id_card': 'തിരിച്ചറിയൽ കാർഡ്',
      'promote': 'ക്ലാസ് പ്രമോഷൻ',
      'certificate': 'ലീവിംഗ് സർട്ടിഫിക്കറ്റ്',
      'maktab_rules': 'മക്തബ് നിയമങ്ങൾ',
      'permissions': 'അനുമതികൾ',
      'db_import_export': 'ഡാറ്റാബേസ് ബാക്കപ്പും പുനഃസ്ഥാപനവും',
      'security_logins': 'സുരക്ഷയും ലോഗിൻ മാനേജ്‌മെന്റും',
      'student_academic_controls': 'വിദ്യാർത്ഥി & അക്കാദമിക് നിയന്ത്രണങ്ങൾ',
      'remember_me': 'Remember Me',
      'forgot_pin': 'Forgot PIN?',
      'login_btn': 'Login',
      'create_account_btn': 'Create Account & Enter',
      'create_account': 'Create Account',
      'biometric_login': 'Biometric Login',
      'last_login': 'Last Successful Login',
      'pin_recovery': 'PIN Recovery',
      'pin_recovery_msg': 'Contact admin or teacher to reset your PIN.',
      'ok': 'OK',
      'account_created': 'Account registered successfully!',
      'error_phone_pin': 'Please enter phone number and PIN',
      'error_name_required': 'Please enter your full name',
      'error_phone_invalid': 'Please enter a valid phone number',
      'error_pin_short': 'PIN must be at least 4 digits',
      'error_pin_mismatch': 'PIN confirmation does not match',
      'error_wrong_pin': 'Wrong phone number or PIN',
      'attempts_remaining': 'Attempts remaining',
      'security_lock': 'Security Lock',
      'seconds_remaining': 'seconds remaining',
      'too_many_attempts': 'Too many failed attempts!',
      'staff_attendance': 'Staff Attendance',
      'staff_attendance_saved': 'Staff Attendance Saved',
      'expenses': 'Income & Expenses',
      'substitute_teacher': 'Substitute Teacher Duty',
      'substitute_desc': 'Assign substitute for absent teacher',
      'dropout_analytics': 'Dropout Register',
      'reason': 'Reason',
      'audit_log': 'Admin History & Logs',
      'select_branch': 'Select Branch',
      'backup_desc': 'Backup or restore all data',
      'class_promotion': 'Class Promotion',
      'promote_confirm': 'Promote all students to next class?',
      'promote_all': 'Promote All',
      'students_promoted': 'All students promoted to next class',
      'leaving_cert': 'Leaving Certificate',
      'add_expense': 'Add Expense',
      'substitute_duty': 'Substitute Duty',
      'code_of_conduct': 'Code of Conduct',
      'rule_punctuality': 'Punctuality is mandatory',
      'rule_dress': 'Come in clean dress with cap',
      'rule_absence': '3 consecutive absences may cancel admission',
      'rule_fee': 'Submit fee by 10th of each month',
      'role_permissions': 'Role-Based Permissions',
      'admin_full_access': 'Admin: Full Access',
      'manager_fees_results': 'Manager: Fees & Results',
      'teacher_attendance_dars': 'Teacher: Attendance & Dars',
      'mutawalli_finance': 'Mutawalli: Financial Auditor',
      'digital_id_card': 'Digital ID Card',
      'position': 'Position',
      'new_admissions': 'New Admissions',
      'old_admissions': 'Old Admissions',
      'hifz_group': 'Hifz Group',
      'nazira_group': 'Nazira Group',
      'tajweed_group': 'Tajweed Group',
      'primary_group': 'Primary Group',
      'morning_shift': 'Morning',
      'evening_shift': 'Evening',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'logout': 'Logout',
      'about': 'About App',
      'version': 'Version',
      'search': 'Search',
      'admin_login': 'Admin Login',
      'manager_login': 'Manager Login',
      'teacher_login': 'Teacher Login',
      'parent_login': 'Parent Login',
      'mutawalli_login': 'Mutawalli Login',
      'user_login': 'User Login',
      'role_tier': 'Tier',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    final dict = _localizedValues[langCode] ?? _localizedValues['ur']!;
    return dict[key] ?? _localizedValues['ur']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ur', 'en', 'ar', 'hi', 'te', 'kn', 'ta', 'ml'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

class LanguageController extends ChangeNotifier {
  static const String _prefKey = 'selected_language_code';
  Locale _locale = const Locale('ur');

  Locale get locale => _locale;

  LanguageController() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final langCode = prefs.getString(_prefKey) ?? 'ur';
      _locale = Locale(langCode);
      notifyListeners();
    } catch (_) {}
  }

  Future<void> setLanguage(String langCode) async {
    if (_locale.languageCode == langCode) return;
    _locale = Locale(langCode);
    notifyListeners();
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_prefKey, langCode);
    } catch (_) {}
  }
}

class LangOption {
  final String code;
  final String nativeScript;
  const LangOption(this.code, this.nativeScript);
}

const List<LangOption> kAllLanguages = [
  LangOption('ur', 'اردو'),
  LangOption('en', 'English'),
  LangOption('ar', 'العربية'),
  LangOption('hi', 'हिंदी'),
  LangOption('te', 'తెలుగు'),
  LangOption('kn', 'ಕನ್ನಡ'),
  LangOption('ta', 'தமிழ்'),
  LangOption('ml', 'മലയാളം'),
];

class LanguageButton extends StatelessWidget {
  final LanguageController controller;

  const LanguageButton({super.key, required this.controller});

  @override
  Widget build(BuildContext context) {
    final loc = AppLocalizations.of(context);
    final currentCode = controller.locale.languageCode;

    return PopupMenuButton<String>(
      icon: const Icon(Icons.language_rounded),
      tooltip: loc.translate('select_language'),
      onSelected: (String langCode) {
        controller.setLanguage(langCode);
      },
      itemBuilder: (BuildContext context) => kAllLanguages.map((lang) {
        final isSelected = currentCode == lang.code;
        return PopupMenuItem<String>(
          value: lang.code,
          child: Row(
            children: [
              Text(
                lang.nativeScript,
                style: TextStyle(
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  color: isSelected ? Theme.of(context).primaryColor : (Theme.of(context).brightness == Brightness.dark ? Colors.white70 : Colors.black87),
                ),
              ),
              if (isSelected) ...[
                const Spacer(),
                Icon(Icons.check_rounded, color: Theme.of(context).primaryColor, size: 18),
              ],
            ],
          ),
        );
      }).toList(),
    );
  }
}

class TranslatedText extends StatefulWidget {
  final String text;
  final TextStyle? style;
  final TextAlign? textAlign;
  final TextDirection? textDirection;
  final int? maxLines;
  final TextOverflow? overflow;

  const TranslatedText(
    this.text, {
    super.key,
    this.style,
    this.textAlign,
    this.textDirection,
    this.maxLines,
    this.overflow,
  });

  @override
  State<TranslatedText> createState() => _TranslatedTextState();
}

class _TranslatedTextState extends State<TranslatedText> {
  String? _translatedText;
  Locale? _lastLocale;

  @override
  Widget build(BuildContext context) {
    final locale = Localizations.localeOf(context);
    final appLoc = AppLocalizations.of(context);
    final localTranslation = appLoc.translate(widget.text);

    if (localTranslation != widget.text) {
      return Text(
        localTranslation,
        style: widget.style,
        textAlign: widget.textAlign,
        textDirection: widget.textDirection,
        maxLines: widget.maxLines,
        overflow: widget.overflow,
      );
    }

    final bool isTest =
    !kIsWeb && std_io.Platform.environment.containsKey('FLUTTER_TEST');
    if (isTest) {
      return Text(
        widget.text,
        style: widget.style,
        textAlign: widget.textAlign,
        textDirection: widget.textDirection,
        maxLines: widget.maxLines,
        overflow: widget.overflow,
      );
    }

    if (_lastLocale != locale) {
      _lastLocale = locale;
      _translatedText = null;
      _fetchTranslation(widget.text, locale.languageCode);
    }

    return Text(
      _translatedText ?? widget.text,
      style: widget.style,
      textAlign: widget.textAlign,
      textDirection: widget.textDirection,
      maxLines: widget.maxLines,
      overflow: widget.overflow,
    );
  }

  Future<void> _fetchTranslation(String text, String targetLang) async {
    // If language is Urdu, keep it as is (default fallback is Urdu in the system)
    if (targetLang == 'ur' || text.trim().isEmpty || RegExp(r'^\d+$').hasMatch(text)) {
      if (mounted) {
        setState(() {
          _translatedText = text;
        });
      }
      return;
    }

    final translated = await GoogleTranslateService.translate(text, targetLang);
    if (mounted) {
      setState(() {
        _translatedText = translated;
      });
    }
  }
}
